spring:
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/trackfaves
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  flyway:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/trackfaves
    user: ${DB_USER}
    password: ${DB_PASSWORD}


logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
#        type.descriptor.sql.BasicBinder: TRACE

manga:
  csv:
    file:
      path: src/main/resources/workload/obras.csv
